USE <DB_NAME>;
DROP TRIGGER IF EXISTS table_token_insert;
DROP TRIGGER IF EXISTS table_token_update;

DROP TRIGGER IF EXISTS table_token_scope_insert;

DROP TRIGGER IF EXISTS table_auth_code_insert;
DROP TRIGGER IF EXISTS table_auth_code_update;

DROP TABLE IDN_OAUTH2_ACCESS_TOKEN_SYNC;
DROP TABLE IDN_OAUTH2_ACCESS_TOKEN_SCOPE_SYNC;
DROP TABLE IDN_OAUTH2_AUTHORIZATION_CODE_SYNC;
COMMIT;